const products=[
{id:1,name:"Galaxy Smartphone",brand:"Samsung",category:"Mobiles",price:24999,rating:4.8,image:"assets/product-01-phone.jpg",badge:"Popular"},
{id:2,name:"MacBook-style Laptop",brand:"Apple",category:"Laptops",price:69999,rating:4.7,image:"assets/product-02-laptop.jpg",badge:"Featured"},
{id:3,name:"Sony Wireless Headphones",brand:"Sony",category:"Audio",price:4999,rating:4.6,image:"assets/product-03-headphones.jpg",badge:"Trending"},
{id:4,name:"boAt Smart Watch",brand:"boAt",category:"Wearables",price:2499,rating:4.4,image:"assets/product-04-watch.jpg"},
{id:5,name:"ASUS Performance Laptop",brand:"ASUS",category:"Laptops",price:58999,rating:4.6,image:"assets/product-05-gaming-laptop.jpg"},
{id:6,name:"OnePlus Wireless Earbuds",brand:"OnePlus",category:"Audio",price:2999,rating:4.5,image:"assets/product-06-earbuds.jpg"},
{id:7,name:"Apple Premium Smartphone",brand:"Apple",category:"Mobiles",price:79999,rating:4.9,image:"assets/product-07-phone.jpg"},
{id:8,name:"Sony Bluetooth Speaker",brand:"Sony",category:"Audio",price:3499,rating:4.3,image:"assets/product-08-speaker.jpg"},
{id:9,name:"Logitech Office Keyboard",brand:"Logitech",category:"Accessories",price:1899,rating:4.4,image:"assets/product-09-keyboard.jpg"},
{id:10,name:"Samsung Portable Tablet",brand:"Samsung",category:"Accessories",price:18999,rating:4.5,image:"assets/product-10-tablet.jpg"},
{id:11,name:"Logitech Wireless Mouse",brand:"Logitech",category:"Accessories",price:999,rating:4.2,image:"assets/product-11-mouse.jpg"},
{id:12,name:"Dell Slim Laptop",brand:"Dell",category:"Laptops",price:47999,rating:4.4,image:"assets/product-12-ultrabook.jpg"}];
let cart=[],wishlist=new Set(),pickedCategory="all",pickedBrand="all";
const $=id=>document.getElementById(id),money=n=>"₹"+n.toLocaleString("en-IN");
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),2600)}
function renderProducts(){const q=$("search").value.toLowerCase().trim(),c=$("category-filter").value,b=$("brand-filter").value,s=$("sort").value;let list=products.filter(p=>(p.name+" "+p.brand+" "+p.category).toLowerCase().includes(q)&&(c==="all"||p.category===c)&&(b==="all"||p.brand===b)&&(pickedCategory==="all"||p.category===pickedCategory)&&(pickedBrand==="all"||p.brand===pickedBrand));if(s==="low")list.sort((a,b)=>a.price-b.price);if(s==="high")list.sort((a,b)=>b.price-a.price);if(s==="name")list.sort((a,b)=>a.name.localeCompare(b.name));$("product-list").innerHTML=list.length?list.map(p=>`<article class="product"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy">${p.badge?`<span class="badge">${p.badge}</span>`:""}<button class="wish ${wishlist.has(p.id)?"active":""}" data-wish="${p.id}" aria-label="Toggle wishlist">${wishlist.has(p.id)?"♥":"♡"}</button></div><div class="product-info"><div class="category">${p.category} · ${p.brand}</div><h3>${p.name}</h3><div class="rating">★★★★★ <span>(${p.rating})</span></div><div class="price-row"><b class="price">${money(p.price)}</b><button class="add" data-add="${p.id}">Add to Cart +</button></div></div></article>`).join(""):'<p class="empty">No matching products found. Try a different filter.</p>'}
function renderCart(){$("cart-count").textContent=cart.reduce((n,p)=>n+p.qty,0);$("total").textContent=money(cart.reduce((n,p)=>n+p.price*p.qty,0));$("cart-items").innerHTML=cart.length?cart.map(p=>`<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h4>${p.name}</h4><p>${money(p.price)}</p><div class="qty"><button data-qty="${p.id}" data-change="-1">−</button><span>${p.qty}</span><button data-qty="${p.id}" data-change="1">+</button></div></div><button class="remove" data-remove="${p.id}">✕</button></div>`).join(""):'<p class="empty">Your cart is empty. Add a product to get started.</p>'}
function add(id){const p=products.find(x=>x.id===+id),item=cart.find(x=>x.id===+id);if(item)item.qty++;else cart.push({...p,qty:1});renderCart();toast(p.name+" added to cart.")}
function openCart(){$("cart").classList.add("open");$("overlay").classList.add("show")}
function closeCart(){$("cart").classList.remove("open");$("overlay").classList.remove("show")}
$("product-list").addEventListener("click",e=>{const a=e.target.closest("[data-add]"),w=e.target.closest("[data-wish]");if(a)add(a.dataset.add);if(w){const id=+w.dataset.wish;if(wishlist.has(id)){wishlist.delete(id);toast("Removed from wishlist.")}else{wishlist.add(id);toast("Added to wishlist.")}renderProducts()}});
$("cart-items").addEventListener("click",e=>{const q=e.target.closest("[data-qty]"),r=e.target.closest("[data-remove]");if(q){const p=cart.find(x=>x.id===+q.dataset.qty);p.qty+=+q.dataset.change;if(p.qty<=0)cart=cart.filter(x=>x.id!==p.id);renderCart()}if(r){cart=cart.filter(x=>x.id!==+r.dataset.remove);renderCart();toast("Product removed.")}});
$("open-cart").onclick=openCart;$("close-cart").onclick=closeCart;$("overlay").onclick=closeCart;
$("checkout").onclick=()=>{if(!cart.length){toast("Your cart is empty.");return}closeCart();$("modal").classList.add("show")};
$("close-modal").onclick=()=>$("modal").classList.remove("show");$("modal").addEventListener("click",e=>{if(e.target===$("modal"))$("modal").classList.remove("show")});
["search","category-filter","brand-filter","sort"].forEach(id=>$(id).addEventListener(id==="search"?"input":"change",()=>{pickedCategory="all";pickedBrand="all";document.querySelectorAll(".categories button,.brands button").forEach(b=>b.classList.remove("active"));renderProducts()}));
document.querySelectorAll(".categories button").forEach(b=>b.onclick=()=>{pickedCategory=b.dataset.category;pickedBrand="all";$("category-filter").value=pickedCategory;$("brand-filter").value="all";document.querySelectorAll(".categories button").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".brands button").forEach(x=>x.classList.remove("active"));renderProducts();$("products").scrollIntoView({behavior:"smooth"})});
document.querySelectorAll(".brands button").forEach(b=>b.onclick=()=>{pickedBrand=b.dataset.brand;pickedCategory="all";$("brand-filter").value=pickedBrand;$("category-filter").value="all";document.querySelectorAll(".brands button").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".categories button").forEach(x=>x.classList.remove("active"));renderProducts();$("products").scrollIntoView({behavior:"smooth"})});
$("contact-form").addEventListener("submit",e=>{e.preventDefault();toast("Demo message submitted successfully.");e.target.reset()});
$("checkout-form").addEventListener("submit",e=>{e.preventDefault();if(!cart.length){$("modal").classList.remove("show");toast("Your cart is empty.");return}const order="TW-"+Date.now().toString().slice(-8),total=cart.reduce((n,p)=>n+p.price*p.qty,0);cart=[];renderCart();$("modal").classList.remove("show");e.target.reset();toast(`Demo order ${order} confirmed · ${money(total)} · No payment taken.`)});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeCart();$("modal").classList.remove("show")}});renderProducts();renderCart();
